name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  P-Checker:
    runs-on: ubuntu-latest
    steps:
      - name: Check P
        run: |
          set
          STUDENT=$(echo ${GITHUB_REPOSITORY##Mospolytech-IIT/labs-})
          lenght_pre=${#GITHUB_REPOSITORY_OWNER}
          lenght_after=${#STUDENT}
          let "lenght_pre += 1"
          let "lenght_after += 1"
          echo "$lenght_pre"
          echo "$lenght_after"
          echo "Надо обрезать от начала на lenght_pre $lenght_pre и от конца на lenght_after $lenght_after"
          REPOSITORY_PREFIX="labs"
          
          echo 'eto prefix='
          echo "$REPOSITORY_PREFIX"
          echo 'eto student='
          echo "$STUDENT"
          PAYLOAD=$(echo '{"organization": "'${GITHUB_REPOSITORY_OWNER}'","repositoryPrefix": "'${REPOSITORY_PREFIX}'","reportFilterRegex": "'${STUDENT}'","fileRegex": ".*.cpp","language": "C","templateRepository": "nastyacat9/Template-CPP-Plagiarism"}')
          echo "$PAYLOAD"
          curl -X 'POST' \
            'https://codeplagiarismapi.azurewebsites.net/api/github' \
            -H 'accept: text/plain' \
            -H 'Content-Type: application/json' \
            -d "$PAYLOAD"